/** 对话公开的具名工具。业务契约及执行权限仍由 Main 的工具适配器校验。 */
export const applicationReadTools = [
  'snapshot',
  'readStudentProfile',
  'studentProfileHistory',
  'readAttendanceRoster',
  'listAttendance',
  'readAttendance',
  'attendanceHistory',
  'listExams',
  'readScoreVersion',
  'scoreHistory',
  'studentScoreHistory',
  'listExplanations',
  'readExplanation',
  'seatingHistory',
  'readSeatingDraft',
  'readSeatingVersion',
  'listDutyPlans',
  'readDutyDraft',
  'dutyHistory',
  'readDutyVersion',
  'listMaterials',
  'readMaterial',
  'listLessonDrafts',
  'readLessonDraft',
  'readLessonVersion',
  'lessonHistory',
  'listClassrooms',
  'readClassroom',
  'readClassroomClock',
  'readCountdown',
  'listRubrics',
  'readRubric',
  'listGradings',
  'readGrading',
  'readGradingReview',
  'gradingAttempts',
  'gradingHistory',
  'readScorePublication',
  'growthTimeline',
  'growthEventHistory',
  'growthSummaryHistory',
  'readGrowthSummary',
  'readDeviceStatus',
  'readStudentCall',
  'readModelSettings',
  'readModelLedger',
] as const;

/** 本地临时草案和预览，不正式写库、外发或打开外部窗口。 */
export const applicationDraftTools = [
  'prepareSeating',
  'adjustSeating',
  'cancelSeating',
  'prepareDuty',
  'adjustDuty',
  'cancelDuty',
  'prepareScorePublication',
] as const;

export const applicationConfirmedTools = [
  'createClass',
  'renameClass',
  'saveStudent',
  'saveStudentProfile',
  'saveAttendance',
  'setStudentActive',
  'saveGrowthEvent',
  'createGrowthSummary',
  'editGrowthSummary',
  'discardGrowthSummary',
  'confirmGrowthSummary',
  'createRubric',
  'createGrading',
  'editGrading',
  'rebindGrading',
  'freezeGrading',
  'confirmScorePublication',
  'createClassroom',
  'controlClassroom',
  'setCountdown',
  'openClassroomDisplay',
  'closeClassroomDisplay',
  'editLessonDraft',
  'createLessonDraft',
  'discardLessonDraft',
  'freezeLessonDraft',
  'reviseLessonVersion',
  'confirmDuty',
  'confirmSeating',
  'editExplanation',
  'discardExplanation',
  'previewSeatingPrint',
  'previewDutyPrint',
  'exportLessonOffice',
  'saveMaterialOriginal',
  'saveBackup',
  'previewRestore',
  'commitRestore',
  'exportDiagnostics',
  'measureNoise',
  'requestStudentCall',
  'cancelDeviceTask',
] as const;
export const applicationToolNames = [
  ...applicationReadTools,
  ...applicationDraftTools,
  ...applicationConfirmedTools,
] as const;
export type ApplicationToolName = (typeof applicationToolNames)[number];
