import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopApi } from '../shared/contracts';

const api: DesktopApi = {
  exportTeachingSeatingImage: (input) => ipcRenderer.invoke('cm:exportTeachingSeatingImage', input),
  listTeachingRecords: (input) => ipcRenderer.invoke('cm:listTeachingRecords', input),
  saveTeachingRecord: (input) => ipcRenderer.invoke('cm:saveTeachingRecord', input),
  deleteTeachingRecord: (input) => ipcRenderer.invoke('cm:deleteTeachingRecord', input),
  readTeachingSettings: (input) => ipcRenderer.invoke('cm:readTeachingSettings', input),
  saveTeachingSettings: (input) => ipcRenderer.invoke('cm:saveTeachingSettings', input),
  exportTeachingReport: (input) => ipcRenderer.invoke('cm:exportTeachingReport', input),
  selectTeachingPhotos: (input) => ipcRenderer.invoke('cm:selectTeachingPhotos', input),
  readTeachingPhoto: (input) => ipcRenderer.invoke('cm:readTeachingPhoto', input),
  saveTeachingExam: (input) => ipcRenderer.invoke('cm:saveTeachingExam', input),
  listBridgeProposals: () => ipcRenderer.invoke('cm:listBridgeProposals'),
  resolveBridgeProposal: (input) => ipcRenderer.invoke('cm:resolveBridgeProposal', input),
  workBuddyConnection: () => ipcRenderer.invoke('cm:workBuddyConnection'),
  openWorkBuddy: () => ipcRenderer.invoke('cm:openWorkBuddy'),
  selectClassData: (input) => ipcRenderer.invoke('cm:selectClassData', input),
  configureClassData: (input) => ipcRenderer.invoke('cm:configureClassData', input),
  confirmClassData: (input) => ipcRenderer.invoke('cm:confirmClassData', input),
  cancelClassData: (input) => ipcRenderer.invoke('cm:cancelClassData', input),
  previewRosterImport: (input) => ipcRenderer.invoke('cm:previewRosterImport', input),
  confirmRosterImport: (input) => ipcRenderer.invoke('cm:confirmRosterImport', input),
  exportRosterTemplate: (input) => ipcRenderer.invoke('cm:exportRosterTemplate', input),
  readStudentProfile: (input) => ipcRenderer.invoke('cm:readStudentProfile', input),
  saveStudentProfile: (input) => ipcRenderer.invoke('cm:saveStudentProfile', input),
  studentProfileHistory: (input) => ipcRenderer.invoke('cm:studentProfileHistory', input),
  readAttendanceRoster: (input) => ipcRenderer.invoke('cm:readAttendanceRoster', input),
  listAttendance: (input) => ipcRenderer.invoke('cm:listAttendance', input),
  readAttendance: (input) => ipcRenderer.invoke('cm:readAttendance', input),
  attendanceHistory: (input) => ipcRenderer.invoke('cm:attendanceHistory', input),
  saveAttendance: (input) => ipcRenderer.invoke('cm:saveAttendance', input),
  onConversationHistoryClose: (listener) => {
    const handle = (_event: Electron.IpcRendererEvent, request: unknown) => {
      if (typeof request !== 'string') return;
      void Promise.resolve()
        .then(listener)
        .then(
          (saved) =>
            ipcRenderer.send('cm:conversationHistoryCloseReady', {
              request,
              saved: saved === true,
            }),
          () => ipcRenderer.send('cm:conversationHistoryCloseReady', { request, saved: false }),
        );
    };
    ipcRenderer.on('cm:conversationHistoryClose', handle);
    ipcRenderer.send('cm:conversationHistoryCloseListening', true);
    return () => {
      ipcRenderer.removeListener('cm:conversationHistoryClose', handle);
      ipcRenderer.send('cm:conversationHistoryCloseListening', false);
    };
  },
  listConversationHistory: (input) => ipcRenderer.invoke('cm:listConversationHistory', input),
  createConversationHistory: (input) => ipcRenderer.invoke('cm:createConversationHistory', input),
  readConversationHistory: (input) => ipcRenderer.invoke('cm:readConversationHistory', input),
  saveConversationHistory: (input) => ipcRenderer.invoke('cm:saveConversationHistory', input),
  renameConversationHistory: (input) => ipcRenderer.invoke('cm:renameConversationHistory', input),
  deleteConversationHistory: (input) => ipcRenderer.invoke('cm:deleteConversationHistory', input),
  prepareConversation: (input) => ipcRenderer.invoke('cm:prepareConversation', input),
  selectConversationFiles: (input) => ipcRenderer.invoke('cm:selectConversationFiles', input),
  removeConversationFiles: (input) => ipcRenderer.invoke('cm:removeConversationFiles', input),
  generateConversation: (input) => ipcRenderer.invoke('cm:generateConversation', input),
  executeConversation: (input) => ipcRenderer.invoke('cm:executeConversation', input),
  readConversation: (input) => ipcRenderer.invoke('cm:readConversation', input),
  cancelConversation: (input) => ipcRenderer.invoke('cm:cancelConversation', input),
  clearConversationSession: (input) => ipcRenderer.invoke('cm:clearConversationSession', input),
  readModelSettings: () => ipcRenderer.invoke('cm:readModelSettings'),
  configureModelProvider: (input) => ipcRenderer.invoke('cm:configureModelProvider', input),
  selectModelProvider: (input) => ipcRenderer.invoke('cm:selectModelProvider', input),
  saveModelProviderKey: (input) => ipcRenderer.invoke('cm:saveModelProviderKey', input),
  deleteModelProviderKey: (input) => ipcRenderer.invoke('cm:deleteModelProviderKey', input),
  prepareModelCheck: (input) => ipcRenderer.invoke('cm:prepareModelCheck', input),
  checkModelProvider: (input) => ipcRenderer.invoke('cm:checkModelProvider', input),
  cancelModelCheck: () => ipcRenderer.invoke('cm:cancelModelCheck'),
  readModelLedger: (input) => ipcRenderer.invoke('cm:readModelLedger', input),
  readDeviceStatus: (input) => ipcRenderer.invoke('cm:readDeviceStatus', input),
  measureNoise: (input) => ipcRenderer.invoke('cm:measureNoise', input),
  requestStudentCall: (input) => ipcRenderer.invoke('cm:requestStudentCall', input),
  readStudentCall: (input) => ipcRenderer.invoke('cm:readStudentCall', input),
  cancelDeviceTask: (input) => ipcRenderer.invoke('cm:cancelDeviceTask', input),
  saveGrowthEvent: (input) => ipcRenderer.invoke('cm:saveGrowthEvent', input),
  growthEventHistory: (input) => ipcRenderer.invoke('cm:growthEventHistory', input),
  growthTimeline: (input) => ipcRenderer.invoke('cm:growthTimeline', input),
  createGrowthSummary: (input) => ipcRenderer.invoke('cm:createGrowthSummary', input),
  prepareGrowthSummary: (input) => ipcRenderer.invoke('cm:prepareGrowthSummary', input),
  generateGrowthSummary: (input) => ipcRenderer.invoke('cm:generateGrowthSummary', input),
  cancelGrowthSummary: (input) => ipcRenderer.invoke('cm:cancelGrowthSummary', input),
  readGrowthSummary: (input) => ipcRenderer.invoke('cm:readGrowthSummary', input),
  editGrowthSummary: (input) => ipcRenderer.invoke('cm:editGrowthSummary', input),
  discardGrowthSummary: (input) => ipcRenderer.invoke('cm:discardGrowthSummary', input),
  confirmGrowthSummary: (input) => ipcRenderer.invoke('cm:confirmGrowthSummary', input),
  growthSummaryHistory: (input) => ipcRenderer.invoke('cm:growthSummaryHistory', input),
  previewGradingPage: (input) => ipcRenderer.invoke('cm:previewGradingPage', input),
  prepareScorePublication: (input) => ipcRenderer.invoke('cm:prepareScorePublication', input),
  confirmScorePublication: (input) => ipcRenderer.invoke('cm:confirmScorePublication', input),
  readScorePublication: (input) => ipcRenderer.invoke('cm:readScorePublication', input),
  createRubric: (input) => ipcRenderer.invoke('cm:createRubric', input),
  readRubric: (input) => ipcRenderer.invoke('cm:readRubric', input),
  listRubrics: (input) => ipcRenderer.invoke('cm:listRubrics', input),
  createGrading: (input) => ipcRenderer.invoke('cm:createGrading', input),
  readGrading: (input) => ipcRenderer.invoke('cm:readGrading', input),
  readGradingReview: (input) => ipcRenderer.invoke('cm:readGradingReview', input),
  listGradings: (input) => ipcRenderer.invoke('cm:listGradings', input),
  editGrading: (input) => ipcRenderer.invoke('cm:editGrading', input),
  rebindGrading: (input) => ipcRenderer.invoke('cm:rebindGrading', input),
  freezeGrading: (input) => ipcRenderer.invoke('cm:freezeGrading', input),
  gradingAttempts: (input) => ipcRenderer.invoke('cm:gradingAttempts', input),
  gradingHistory: (input) => ipcRenderer.invoke('cm:gradingHistory', input),
  prepareGrading: (input) => ipcRenderer.invoke('cm:prepareGrading', input),
  generateGrading: (input) => ipcRenderer.invoke('cm:generateGrading', input),
  cancelGrading: (input) => ipcRenderer.invoke('cm:cancelGrading', input),
  createClassroom: (input) => ipcRenderer.invoke('cm:createClassroom', input),
  readClassroom: (input) => ipcRenderer.invoke('cm:readClassroom', input),
  listClassrooms: (input) => ipcRenderer.invoke('cm:listClassrooms', input),
  controlClassroom: (input) => ipcRenderer.invoke('cm:controlClassroom', input),
  readClassroomClock: (input) => ipcRenderer.invoke('cm:readClassroomClock', input),
  readCountdown: (input) => ipcRenderer.invoke('cm:readCountdown', input),
  setCountdown: (input) => ipcRenderer.invoke('cm:setCountdown', input),
  openClassroomDisplay: (input) => ipcRenderer.invoke('cm:openClassroomDisplay', input),
  closeClassroomDisplay: (input) => ipcRenderer.invoke('cm:closeClassroomDisplay', input),
  exportLessonOffice: (input) => ipcRenderer.invoke('cm:exportLessonOffice', input),
  cancelLessonOffice: (input) => ipcRenderer.invoke('cm:cancelLessonOffice', input),
  openLessonOffice: (input) => ipcRenderer.invoke('cm:openLessonOffice', input),
  previewMaterial: (input) => ipcRenderer.invoke('cm:previewMaterial', input),
  scanMaterialFolder: (input) => ipcRenderer.invoke('cm:scanMaterialFolder', input),
  readMaterialFolder: (input) => ipcRenderer.invoke('cm:readMaterialFolder', input),
  cancelMaterialFolder: (input) => ipcRenderer.invoke('cm:cancelMaterialFolder', input),
  openResourceLink: (input) => ipcRenderer.invoke('cm:openResourceLink', input),
  confirmMaterial: (input) => ipcRenderer.invoke('cm:confirmMaterial', input),
  cancelMaterial: (input) => ipcRenderer.invoke('cm:cancelMaterial', input),
  readMaterialPreviewImage: (input) => ipcRenderer.invoke('cm:readMaterialPreviewImage', input),
  readMaterial: (input) => ipcRenderer.invoke('cm:readMaterial', input),
  listMaterials: (input) => ipcRenderer.invoke('cm:listMaterials', input),
  readMaterialImage: (input) => ipcRenderer.invoke('cm:readMaterialImage', input),
  saveMaterialOriginal: (input) => ipcRenderer.invoke('cm:saveMaterialOriginal', input),
  prepareLesson: (input) => ipcRenderer.invoke('cm:prepareLesson', input),
  createLessonDraft: (input) => ipcRenderer.invoke('cm:createLessonDraft', input),
  readSeatingDraft: (input) => ipcRenderer.invoke('cm:readSeatingDraft', input),
  readDutyDraft: (input) => ipcRenderer.invoke('cm:readDutyDraft', input),
  generateLesson: (input) => ipcRenderer.invoke('cm:generateLesson', input),
  cancelLesson: (input) => ipcRenderer.invoke('cm:cancelLesson', input),
  readLessonDraft: (input) => ipcRenderer.invoke('cm:readLessonDraft', input),
  listLessonDrafts: (input) => ipcRenderer.invoke('cm:listLessonDrafts', input),
  editLessonDraft: (input) => ipcRenderer.invoke('cm:editLessonDraft', input),
  discardLessonDraft: (input) => ipcRenderer.invoke('cm:discardLessonDraft', input),
  freezeLessonDraft: (input) => ipcRenderer.invoke('cm:freezeLessonDraft', input),
  readLessonVersion: (input) => ipcRenderer.invoke('cm:readLessonVersion', input),
  lessonHistory: (input) => ipcRenderer.invoke('cm:lessonHistory', input),
  reviseLessonVersion: (input) => ipcRenderer.invoke('cm:reviseLessonVersion', input),
  prepareDuty: (input) => ipcRenderer.invoke('cm:prepareDuty', input),
  adjustDuty: (input) => ipcRenderer.invoke('cm:adjustDuty', input),
  cancelDuty: (input) => ipcRenderer.invoke('cm:cancelDuty', input),
  confirmDuty: (input) => ipcRenderer.invoke('cm:confirmDuty', input),
  dutyHistory: (input) => ipcRenderer.invoke('cm:dutyHistory', input),
  readDutyVersion: (input) => ipcRenderer.invoke('cm:readDutyVersion', input),
  listDutyPlans: (input) => ipcRenderer.invoke('cm:listDutyPlans', input),
  previewSeatingPrint: (input) => ipcRenderer.invoke('cm:previewSeatingPrint', input),
  previewDutyPrint: (input) => ipcRenderer.invoke('cm:previewDutyPrint', input),
  prepareSeating: (input) => ipcRenderer.invoke('cm:prepareSeating', input),
  adjustSeating: (input) => ipcRenderer.invoke('cm:adjustSeating', input),
  cancelSeating: (input) => ipcRenderer.invoke('cm:cancelSeating', input),
  confirmSeating: (input) => ipcRenderer.invoke('cm:confirmSeating', input),
  seatingHistory: (input) => ipcRenderer.invoke('cm:seatingHistory', input),
  readSeatingVersion: (input) => ipcRenderer.invoke('cm:readSeatingVersion', input),
  prepareExplanation: (input) => ipcRenderer.invoke('cm:prepareExplanation', input),
  generateExplanation: (input) => ipcRenderer.invoke('cm:generateExplanation', input),
  cancelExplanation: (input) => ipcRenderer.invoke('cm:cancelExplanation', input),
  readExplanation: (input) => ipcRenderer.invoke('cm:readExplanation', input),
  listExplanations: (input) => ipcRenderer.invoke('cm:listExplanations', input),
  editExplanation: (input) => ipcRenderer.invoke('cm:editExplanation', input),
  discardExplanation: (input) => ipcRenderer.invoke('cm:discardExplanation', input),
  snapshot: () => ipcRenderer.invoke('cm:snapshot'),
  createClass: (input) => ipcRenderer.invoke('cm:createClass', input),
  renameClass: (input) => ipcRenderer.invoke('cm:renameClass', input),
  saveStudent: (input) => ipcRenderer.invoke('cm:saveStudent', input),
  setStudentActive: (input) => ipcRenderer.invoke('cm:setStudentActive', input),
  seedDemo: (input) => ipcRenderer.invoke('cm:seedDemo', input),
  addSyntheticAsset: (input) => ipcRenderer.invoke('cm:addSyntheticAsset', input),
  saveBackup: (input) => ipcRenderer.invoke('cm:saveBackup', input),
  previewRestore: () => ipcRenderer.invoke('cm:previewRestore'),
  previewRecovery: () => ipcRenderer.invoke('cm:previewRecovery'),
  commitRestore: (input) => ipcRenderer.invoke('cm:commitRestore', input),
  exportDiagnostics: () => ipcRenderer.invoke('cm:exportDiagnostics'),
  getDeepSeekStatus: () => ipcRenderer.invoke('cm:getDeepSeekStatus'),
  saveDeepSeekKey: (input) => ipcRenderer.invoke('cm:saveDeepSeekKey', input),
  deleteDeepSeekKey: () => ipcRenderer.invoke('cm:deleteDeepSeekKey'),
  checkDeepSeek: (input) => ipcRenderer.invoke('cm:checkDeepSeek', input),
  cancelDeepSeekCheck: () => ipcRenderer.invoke('cm:cancelDeepSeekCheck'),
  getDeepSeekLedger: () => ipcRenderer.invoke('cm:getDeepSeekLedger'),
  previewScores: (input) => ipcRenderer.invoke('cm:previewScores', input),
  confirmScores: (input) => ipcRenderer.invoke('cm:confirmScores', input),
  cancelScorePreview: (input) => ipcRenderer.invoke('cm:cancelScorePreview', input),
  listExams: (input) => ipcRenderer.invoke('cm:listExams', input),
  readScoreVersion: (input) => ipcRenderer.invoke('cm:readScoreVersion', input),
  scoreHistory: (input) => ipcRenderer.invoke('cm:scoreHistory', input),
  studentScoreHistory: (input) => ipcRenderer.invoke('cm:studentScoreHistory', input),
  exportScoreTemplate: (input) => ipcRenderer.invoke('cm:exportScoreTemplate', input),
};
contextBridge.exposeInMainWorld('classManager', Object.freeze(api));
