import { createHash, randomUUID } from 'node:crypto';
import {
  LESSON_LIMITS,
  MATERIAL_IMAGE_LIMITS,
  MATERIAL_MIME,
  materialVersionSchema,
  type MaterialFragment,
  type MaterialVersion,
} from '../shared/lessons';
import { DomainError } from './errors';
import { extractDocxMaterial } from './material-docx';
import { decodeMaterialImage } from './material-image';
import { parseTextMaterial } from './material-text';
import { extractPdfMaterial } from './material-pdf';

export interface ParsedMaterial {
  version: MaterialVersion;
  assets: { id: string; mime: string; bytes: Buffer }[];
}
const hash = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');

/**
 * Private parser boundary: original bytes plus normalized, independently addressable images.
 * No persistence, user path access or remote requests; call only in an isolated task.
 * The original is retained for teacher comparison, never implicitly approved for model upload.
 * PDF pages are rendered and text is extracted without OCR; partial warnings must be acknowledged.
 */
export async function parseMaterial(
  bytes: Buffer,
  format: MaterialVersion['format'],
): Promise<ParsedMaterial> {
  if (!Buffer.isBuffer(bytes) || !bytes.length || bytes.length > LESSON_LIMITS.fileBytes)
    throw new DomainError('MATERIAL_INVALID', '资料为空或超过 10 MiB。');
  const originalAssetId = randomUUID();
  const mime = Object.hasOwn(MATERIAL_MIME, format) ? MATERIAL_MIME[format] : undefined;
  if (!mime) throw new DomainError('MATERIAL_INVALID', '不支持该资料格式。');
  const assets: ParsedMaterial['assets'] = [
    { id: originalAssetId, mime, bytes: Buffer.from(bytes) },
  ];
  let fragments: MaterialFragment[] = [];
  let completeness: MaterialVersion['completeness'] = 'complete';
  let warnings: string[] = [];
  let derivedBytes = 0;
  function appendImage(
    image: { bytes: Buffer; width: number; height: number; mime: string },
    locator: MaterialFragment['locator'],
  ) {
    derivedBytes += image.bytes.length;
    if (derivedBytes > MATERIAL_IMAGE_LIMITS.totalOutputBytes)
      throw new DomainError('MATERIAL_INVALID', '资料标准化图片累计超过 64 MiB，请拆分资料。');
    const assetId = randomUUID();
    assets.push({ id: assetId, mime: image.mime, bytes: image.bytes });
    fragments.push({
      kind: 'image',
      id: fragments.length + 1,
      locator,
      assetId,
      sha256: hash(image.bytes),
      width: image.width,
      height: image.height,
    });
  }
  async function imagePart(
    source: Buffer,
    kind: 'png' | 'jpg',
    locator: MaterialFragment['locator'],
  ) {
    appendImage(await decodeMaterialImage(source, kind), locator);
  }
  if (format === 'txt') fragments = parseTextMaterial(bytes);
  else if (format === 'jpg' || format === 'png')
    await imagePart(bytes, format, { kind: 'page', index: 1 });
  else if (format === 'docx') {
    const docx = await extractDocxMaterial(bytes);
    completeness = docx.completeness;
    warnings = docx.warnings;
    for (const part of docx.parts) {
      const locator = { kind: 'paragraph' as const, index: part.paragraph };
      if (part.kind === 'image') await imagePart(part.bytes, part.format, locator);
      else fragments.push({ kind: 'text', id: fragments.length + 1, locator, text: part.text });
    }
  } else {
    const pdf = await extractPdfMaterial(bytes);
    completeness = pdf.completeness;
    warnings = pdf.warnings;
    for (const part of pdf.parts) {
      const locator = { kind: 'page' as const, index: part.page };
      // Page PNGs were generated by our bounded canvas, not uploaded as 10 MiB image files.
      if (part.kind === 'image') appendImage({ ...part, mime: 'image/png' }, locator);
      else fragments.push({ kind: 'text', id: fragments.length + 1, locator, text: part.text });
    }
  }
  const version = materialVersionSchema.parse({
    id: randomUUID(),
    originalAssetId,
    format,
    sha256: hash(bytes),
    bytes: bytes.length,
    completeness,
    warnings,
    fragments,
  });
  return { version, assets };
}
